### ISSUE TITLE
compile with error on gcc5.3

### ISSUE THREAD

**Issue by ho1messi** [ArthurSonzogni/FTXUI#265]
I download the v0.11 source, when I try to build I got this error:

```
In file included from .../FTXUI-0.11/include/ftxui/dom/elements.hpp:131:0,
                 from .../FTXUI-0.11/src/ftxui/dom/blink.cpp:4:
.../FTXUI-0.11/include/ftxui/dom/take_any_args.hpp: In function ‘ftxui::Elements ftxui::unpack(Args ...)’:
.../FTXUI-0.11/include/ftxui/dom/take_any_args.hpp:24:33: error: expected primary-expression before ‘...’ token
   (Merge(vec, std::move(args)), ...);
                                 ^
.../FTXUI-0.11/include/ftxui/dom/take_any_args.hpp:24:33: error: expected ‘)’ before ‘...’ token
.../FTXUI-0.11/include/ftxui/dom/take_any_args.hpp:24:37: error: parameter packs not expanded with ‘...’:
   (Merge(vec, std::move(args)), ...);
                                     ^
.../FTXUI-0.11/include/ftxui/dom/take_any_args.hpp:24:37: note:         ‘args’
make[2]: *** [CMakeFiles/dom.dir/src/ftxui/dom/blink.cpp.o] Error 1
make[1]: *** [CMakeFiles/dom.dir/all] Error 2
make: *** [all] Error 2
```

my gcc version is 5.3.1, and in another computer with gcc8.5 it's ok.
