### ISSUE TITLE
4.1.0 changes public interface (non-semver API change?)

### ISSUE THREAD

**Issue by KerstinKeller** [ArthurSonzogni/FTXUI#649]
It seems that the latest FTXUI release breaks our eCAL Build, which worked fine with FTXUI 4.0.0.

We have the following code
https://github.com/eclipse-ecal/ecal/blob/6fc81d074bc3d5918df8378e56c6bb3134a26e95/app/mon/mon_tui/src/tui/style_sheet.hpp#LL212C1-L212C45

which seems to break with the latest Release (see also this issue https://github.com/eclipse-ecal/ecal/issues/1108)
```
In file included from /wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/main.cpp:29:
In file included from /wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/tui/tui.hpp:31:
/wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/tui/style_sheet.hpp:113:39: error: no member named 'Right' in 'ftxui::MenuOption'
    sheet.tab.direction = MenuOption::Right;
                          ~~~~~~~~~~~~^
/wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/tui/style_sheet.hpp:212:39: error: no member named 'Right' in 'ftxui::MenuOption'
    sheet.tab.direction = MenuOption::Right;
                          ~~~~~~~~~~~~^
```

The changes were introduced in the following commit 
https://github.com/ArthurSonzogni/FTXUI/commit/9b074d1e27a9fa069d55dee23d75fd8ce4df885a

Do you have a suggestion how we can fix this in a backwards compatible way (e.g. works with both < 4.0.0 and >= 4.1.0 versions)?
Or can you release a 4.1.1 which makes the enum still available in the `MenuOption` namespace, with some `using` directives? 

Since this is public API breaking, I would expect a change like this rather for a new major, rather than a minor release version.

**Comment by ArthurSonzogni** [comment]
You are right. I made a mistake when cherry-picking this patch into v4.1.0.

Not sure what's best from here. Unpublish v4.1.0 and release v4.1.1?

**Comment by FlorianReimold** [comment]
Please **don't** change the reference of tag v4.1.0. If you do that, people will have v4.1.0 checked out without knowing if they have the old or now 4.1.0. Just increase the latest number and make it v4.1.1. The latest number is meant to be increased when patching, so it is meant exactly for this purpose.
You will never ever run out of numbers, so please don't be afraid to use them. There will always be plenty left 😉

**Comment by ArthurSonzogni** [comment]
v4.1.1 is going to be a breaking change relative to v4.1.0.

I think I am going to keep the v4.1.0 git tag, but unpublish the release from github.

**Comment by ArthurSonzogni** [comment]
Hi @KerstinKeller & @FlorianReimold

The branch https://github.com/ArthurSonzogni/FTXUI/tree/support-v4 is going to become v4.1.1. It should be good and not breaking v4.0.0. This time, I won't rush. Could you please take a look and tell if this is good?

Unfortunately, there was no way to have a "soft" fix without breaking v4.1.0. That's because the breaking change renamed both Direction into WithOrHeight and GaugeDirection into Direction. We can't have `Direction` means multiple incompatible enums.

**Comment by FlorianReimold** [comment]
I updated to the current HEAD of support-v4 in a branch in our eCAL Repository. The results will ready in in about 1h or so:

https://github.com/eclipse-ecal/ecal/tree/testing/ftxui_4.1.1

Ubuntu 20.04: https://github.com/eclipse-ecal/ecal/actions/runs/5089121687/jobs/9146373055
Ubuntu 22.04: https://github.com/eclipse-ecal/ecal/actions/runs/5089121663/jobs/9146373082
Windows (VS 2019): https://github.com/eclipse-ecal/ecal/actions/runs/5089121665/jobs/9146373351
macOS: https://github.com/eclipse-ecal/ecal/actions/runs/5089121666/jobs/9146373086

**Comment by ArthurSonzogni** [comment]
Thanks!

The macOS version had an issue, because C++17 was not applied to the dependant (ecal). I pushed a few more CLs to fix the issue. If you can retry before I publish it, it would be greatly appreciated! (@FlorianReimold)

**Comment by ArthurSonzogni** [comment]
I think the fix was good, so I will publish v4.1.1

**Comment by ArthurSonzogni** [comment]
https://github.com/ArthurSonzogni/FTXUI/releases/tag/v4.1.1

**Comment by FlorianReimold** [comment]
> The macOS version had an issue, because C++17 was not applied to the dependant (ecal).

Yep, I realized the mistake and pushed another commit that I didn't like here. Just going to C++17 worked well for macOS

> If you can retry before I publish it, it would be greatly appreciated! (@FlorianReimold)

Well, that probably is too late now 😀
But I updated to the 4.1.1 tag you released:

Ubuntu 20.04: https://github.com/eclipse-ecal/ecal/actions/runs/5118599237/jobs/9202815300
Ubuntu 22.04: https://github.com/eclipse-ecal/ecal/actions/runs/5118599220/jobs/9202815520
Windows: https://github.com/eclipse-ecal/ecal/actions/runs/5118599226/jobs/9202815385
macOS: https://github.com/eclipse-ecal/ecal/actions/runs/5118599221/jobs/9202815295
